# This is a basic workflow to help you get started with Actions

name: Unit_Tests-

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request on main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    strategy:
      matrix: 
        version: [latest, R2023b, R2022b, 2021a]
        os: [ubuntu-latest, windows-latest]
      
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with: 
          release: ${{ matrix.version }}

      - name: Run tests
        uses: matlab-actions/run-tests@v2